name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, devel]
    
defaults:
  run:
    working-directory: ./
    
jobs:
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build_App
        run: docker-compose up --build

  test:
      name: Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Build_App
          run: docker-compose up --build
        - uses: docker://library_app
        - name: Run_tests
          run: python manage.py test
