name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: docker-compose up --build -d

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Backend tests
        run: docker-compose run library_app sh -c "python manage.py migrate && python manage.py test"
        
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Backend Lint
        run: docker-compose run library_app sh -c "pylint manage.py src/settings.py src/urls.py src/wsgi.py --disable=C"

  cd:
    name: CD
    runs-on: ubuntu-latest
    needs:
      - lint
      - tests
      - build
    
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        env:
          USER: ${{secrets.DOCKER_USER}}
          PSW: ${{secrets.DOCKER_PSW}}
        run: docker login -u $USER -p $PSW
        
      - name: Build app image
        run: docker compose build library_app
      
      - name: Build front image
        run: docker compose build library_front
      
      - name: Tag app image
        run: docker tag library_app:local ${{secrets.DOCKER_USER}}/app:$(date +%s)
      
      - name: Tag front image
        run: docker tag library_front:local ${{secrets.DOCKER_USER}}/front:$(date +%s)
     
      - name: Docker push app image
        run: docker push ${{secrets.DOCKER_USER}}/app:$(date +%s)
      
      - name: Docker push front image
        run: docker push ${{secrets.DOCKER_USER}}/front:$(date +%s)
      
    
