name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, devel]
    
defaults:
  run:
    working-directory: ./
    
jobs:
  build_app: 
    name: Build_app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build_DB
        run: docker-compose up library_db
      - name: Build_App
        run: docker-compose up library_app

  test_app:
      name: Test_app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Build_DB
          run: docker-compose up library_db
        - name: Test_App
          run: docker-compose up library_app bash -c "python manage.py test"
